import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { DragDropHandlerComponent } from './components/drag-drop-handler.component';
import { FileInputComponent } from './components/file-input.component';

export * from './components/drag-drop-handler.component';
export * from './components/file-input.component';

@NgModule({
  imports: [ CommonModule ],
  declarations: [
    FileInputComponent,
    DragDropHandlerComponent
  ],
  exports: [
    FileInputComponent,
    DragDropHandlerComponent
  ]
})
export class FileDropModule {}

// Module as it was generated by generator-ngx-library:
// import { CommonModule } from '@angular/common';
// import { NgModule, ModuleWithProviders } from '@angular/core';

// import { LibComponent } from './component/lib.component';
// import { LibService } from './service/lib.service';

// // Export module's public API
// export { LibComponent } from './component/lib.component';
// export { LibService } from './service/lib.service';

// @NgModule({
//   imports: [
//     CommonModule
//   ],
//   exports: [LibComponent],
//   declarations: [LibComponent]
// })
// export class LibModule {
//   static forRoot(): ModuleWithProviders {
//     return {
//       ngModule: LibModule,
//       providers: [LibService]
//     };
//   }
// }
